plugins {
    id 'dev.architectury.loom-no-remap'
    id 'dev.architectury.loom'
    id 'io.github.brainage04.workspace-dependencies' version "${fabricmoddingconventions_version}"
}
sourceSets {
    main {
        java.srcDir rootProject.file('src/main/java')
        resources.srcDir rootProject.file('src/main/resources')
        resources.exclude 'fabric.mod.json'
    }
}
workspaceDependencies {
    siblingMaven('BrainageLib') {
        coordinate.set("io.github.brainage04:brainagelib:${rootProject.brainagelib_version}")
        siblingDirectory.set(rootProject.layout.projectDirectory.dir('../BrainageLib'))
    }
}
dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    compileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}"
    compileOnly "io.github.brainage04:brainagelib:${rootProject.brainagelib_version}"
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test { useJUnitPlatform() }
