modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="vein_miner"
version="${version}"
displayName="Vein Miner"
description='''Mines connected ore and tree blocks using per-player activation and selection controls.'''
authors="brainage04"

[[dependencies.vein_miner]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.vein_miner]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.vein_miner]]
modId="brainagelib"
type="required"
versionRange="[${brainagelib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.vein_miner]]
modId="telekinesis"
type="optional"
versionRange="*"
ordering="NONE"
side="BOTH"

[[mixins]]
config="vein_miner.neoforge.mixins.json"

[[mixins]]
config="vein_miner.mixins.json"
