workspaceDependencies {
	siblingMaven('BrainageLib') {
		coordinate.set("io.github.brainage04:brainagelib-neoforge:${rootProject.brainagelib_version}")
		siblingDirectory.set(rootProject.layout.projectDirectory.dir('../BrainageLib'))
	}
}

dependencies { implementation "io.github.brainage04:brainagelib-neoforge:${rootProject.brainagelib_version}" }
