name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  prepare:
    permissions:
      contents: write
    uses: brainage04/FabricModdingConventions/.github/workflows/reusable-release-prepare.yml@v2.3.1
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}

  github:
    needs: prepare
    permissions:
      contents: write
    uses: brainage04/FabricModdingConventions/.github/workflows/reusable-publish-github.yml@v2.3.1
    with:
      artifact_file: ${{ needs.prepare.outputs.artifact_file }}
      release_body: ${{ needs.prepare.outputs.release_body }}
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}

  modrinth:
    needs: prepare
    permissions:
      contents: read
    uses: brainage04/FabricModdingConventions/.github/workflows/reusable-publish-modrinth.yml@v2.3.1
    with:
      artifact_file: ${{ needs.prepare.outputs.artifact_file }}
      release_body: ${{ needs.prepare.outputs.release_body }}
      project_id: ${{ vars.MODRINTH_PROJECT_ID }}
    secrets:
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}

  curseforge:
    needs: prepare
    permissions:
      contents: read
    uses: brainage04/FabricModdingConventions/.github/workflows/reusable-publish-curseforge.yml@v2.3.1
    with:
      artifact_file: ${{ needs.prepare.outputs.artifact_file }}
      release_body: ${{ needs.prepare.outputs.release_body }}
      project_id: ${{ vars.CURSEFORGE_PROJECT_ID }}
      project_slug: vein-miner
    secrets:
      curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
